### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by gthvidsten** [thoemmi/StickyWindows#2]
This isn't as much an issue as a general question.

Moving and resizing works just fine in WinForms and WPF, but what about UWP apps?
Will this work by default with UWP apps, or do you need to add UWP support?

If the latter, are there any plans on doing that, and how soon? :)

**Comment by thoemmi** [comment]
I am afraid that it's not possible. StickyWindows relies on System.Windows.Forms, and that's .NET Framework only. UWP apps on the other hand use .NET Core. There might exist hacks to get it working, but you wouldn't pass the Windows Store certification.
