### ISSUE TITLE
Does not work with MahApps.Metro

### ISSUE THREAD

**Issue by JobaDiniz** [thoemmi/StickyWindows#7]
[MahApps.Metro](https://github.com/MahApps/MahApps.Metro) changes the window border and StickyWindow doesn't work in [MetroWindow](https://github.com/MahApps/MahApps.Metro/blob/1.6.5/src/MahApps.Metro/Controls/MetroWindow.cs).

Any insights on how to address this issue? I'm able to help with pull-request.

**Comment by thoemmi** [comment]
This is caused by MahApps.Metro. There's an old PR which has not been merged yet: https://github.com/MahApps/MahApps.Metro/pull/2822
